### ISSUE TITLE
Scroll blocked in training courses

### ISSUE THREAD

**Issue by fuunnx** [enkidevs/feedback#23]
While doing the training courses, the scroll view block and I can't move up or down for a few seconds.

Device: Oneplus One, Android L, Cyanogenmod

**Comment by spypsy** [comment]
Hello, thanks for your feedback. We fixed this bug today and deployed the newest version. It should work the next time you use the app! Please let us know if that's not the case. 

By the way, we are closing this repo as we found that github is not the best channel for products without the code. For any other issues you might encounter or suggestions you want to make, please head over to productpains.com/product/enki Thanks!
