### ISSUE TITLE
Feedback screen not hiding

### ISSUE THREAD

**Issue by fuunnx** [enkidevs/feedback#24]
After submitting my feedback, the feedback screen does not hide automatically.
I have to press the back button which get me back to the launcher. Then I have to switch back to the application.

Device: Oneplus One, Android L, Cyanogenmod

**Comment by spypsy** [comment]
Just to clarify, was this after a game feedback? If so, we fixed this today and deployed the newest version. It should work the next time you use the app. If not, please head over to https://productpains.com/product/enki and let us know!
